In [2]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.3-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.1.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (8.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.56.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.8.0+cu126)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.34.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.1.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.8.3)
Downloading bertopic-0.17.3-py3-none-any.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.0/153.0 kB 4.3 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.3

In [4]:
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, OpenAI, PartOfSpeech
from bertopic.vectorizers import ClassTfidfTransformer
import nltk
from nltk.tokenize import sent_tokenize
import pandas as pd
from bertopic import BERTopic
import re
from umap import UMAP
from sentence_transformers import SentenceTransformer

/usr/local/lib/python3.12/dist-packages/hdbscan/plots.py:448: SyntaxWarning: invalid escape sequence '\l'
  axis.set_ylabel('$\lambda$ value')
/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.

In [5]:
import pandas as pd
from IPython.display import display

In [6]:
def display_dataframe_with_scroll(df, max_height=400, max_width=1000):
    styled_df = df.style.set_sticky()  # Makes the header and index sticky
    display(styled_df.set_table_attributes(f"style='display:inline; overflow:auto; max-height:{max_height}px; max-width:{max_width}px;'"))

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
df = "/content/drive/MyDrive/topic-specific-corpus-creation/pickle_files/diarium.pk"

In [12]:
df_digi = pd.read_pickle(df)

In [13]:
df_digi

             date                                               text
0      1703-08-13                Auss Wienn von  biss  Augusti 1703.
1      1703-08-13  DEn  dito hat man dass die Land Militz welche ...
2      1703-08-13                      Wie verlautet seynd  Käyserl.
3      1703-08-13  in   stehende Regimenter beordert ihren March ...
4      1703-08-13  Gestern ist ein Courier von der Armée auss Jta...
...           ...                                                ...
79777  1798-10-03  Praktische französische Grammatik, wodurch man...
79778  1798-10-03  Von Johann Valentin Meidinger, Lehrer der fran...
79779  1798-10-03  Fünfzehnte durchaus verbesserte und nach Waill...
79780  1798-10-03                        Frankfurt und Leipzig 1799.
79781  1798-10-03  38 Bogen stark, auf schönen weissen Druckpapie...

[79782 rows x 2 columns]

In [14]:
df_digi["date"] = pd.to_datetime(df_digi["date"], errors="raise")

## Number of words

In [15]:
df_digi['word_count'] = df_digi['text'].apply(lambda x: len(x.split()))

# Calculate average, max, and min number of words
average_words = df_digi['word_count'].mean()
max_words = df_digi['word_count'].max()
min_words = df_digi['word_count'].min()

# Print the results
print(f"Average number of words: {average_words}")
print(f"Maximum number of words: {max_words}")
print(f"Minimum number of words: {min_words}")

Average number of words: 27.449963650948835
Maximum number of words: 590
Minimum number of words: 1

## Read tokenized file

### With GPT-4o as representation

In [ ]:
import openai
from bertopic.representation import OpenAI
from bertopic import BERTopic

In [ ]:
client = openai.OpenAI(api_key = '')

In [ ]:
representation_model = OpenAI(client, prompt)

NameError: name 'prompt' is not defined

## Topic modelling

In [ ]:
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)

In [ ]:
embedding_model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
keywords_minorities = [
    "juden", "ungarn", "böhmen", "kroaten", "serben", "slowaken", "deutsche",
    "rumänen", "zigeuner", "roma", "griechen", "osmanen", "türken", 'hungarn', 'czech', 'pol', 'kroat', 'kroatien', 'balkan','serbien', 'dalmatien', 'bosnien', 'slowak', 'magyar',
        'slowen', 'türken', 'juden', 'landjuden', 'toleranzjuden', 'ghettobewohner',
        'israeliten', 'händlerjuden', 'wechsler', 'deutschen'
]

keywords_migration = [
    "fremd", "zuwanderer", "emigrant", "flüchtling", "einwanderung",
    "auswanderung", "ansiedlung", "siedler", "vertreibung", "exil", "heimat", 'auswandern', 'auswanderung', 'übersiedlung', 'wandern', 'einwanderung',
        'flüchtling', 'hausierer', 'arbeiter', 'einwanderer', 'einwandern', 'gesinde', 'migrant', 'böheim', "fremdling"
]

keywords_nationalism = [
    "patriotismus", "vaterlandsliebe", "identität", "staatsgesinnung",
    "vaterland", "nation", "volk", "heimat", "volksgeist", "land", 'sprache', 'vaterlandsliebe', 'identität', 'serb', 'deutschtum', 'staatsgesinnung',
        'volksgeist', 'sprache'
]

keywords_work = [
    "arbeit", "arbeiter", "handwerker", "gesinde", "dienstboten", "tagelöhner",
    "beruf", "werkstatt", "meister", "fabrik", "produktion", "wirtschaft",
    "industrie", "gewerbe", "lohn", "beschäftigung", "händler", "handwerk", "hausierer"


]

keywords_jews = [
    "juden", "landjuden", "toleranzjuden", "ghettobewohner", "israeliten",
    "händlerjuden", "wechsler", "schutzjuden", "pachtsjuden", "betteljude",
    "synagoge", "rabbinus", "judentum", "gemeindevorsteher", "exil", "vertrieben"
]


# Combine all unique keywords from work, Jewish, migration, minorities, and nationalism into one list
all_keywords = list(set(keywords_work + keywords_jews + keywords_minorities + keywords_migration + keywords_nationalism))

# Sort the combined list alphabetically for easier readability
all_keywords.sort()

In [ ]:
ctfidf_model = ClassTfidfTransformer(
    seed_words=keywords_minorities,
    seed_multiplier=15
)

- Seedwords 1 + 2 = Fremd', 'Flüchtling', 'Hausiere',' Arbeiter', 'Einwanderer', 'einwandern', 'Zuwanderer', 'Czech', 'Pol', 'Kroat', 'Balkan', 'Serb','bosnien','slowak', 'magyar', 'slowen','türken', 'Juden', 'Deutschen', 'Arbeit', 'Sprache'
- seedwords 2-5 hungarn', 'czech', 'pol', 'kroat', 'kroatien', 'balkan', 'patriotismus',
        'vaterlandsliebe', 'identität', 'serb', 'deutschtum', 'staatsgesinnung',
        'volksgeist', 'serbien', 'dalmatien', 'bosnien', 'slowak', 'magyar',
        'slowen', 'türken', 'juden', 'landjuden', 'toleranzjuden', 'ghettobewohner',  
        'israeliten', 'händlerjuden', 'wechsler', 'deutschen', 'arbeit', 'sprache',     'fremd', 'fremdling', 'zuwanderer', 'gesinde', 'migrant', 'böheim',
        'auswandern', 'auswanderung', 'übersiedlung', 'wandern', 'einwanderung',
        'flüchtling', 'hausierer', 'arbeiter', 'einwanderer', 'einwandern',

In [ ]:
topic_model_migra = BERTopic(verbose=True, embedding_model=embedding_model, language = "multilingual",ctfidf_model=ctfidf_model, umap_model=umap_model,min_topic_size=15)

In [16]:
timestamps  = df_digi.date.to_list()
texts = df_digi.text.to_list()

In [ ]:
prompt = "I have the following documents: [DOCUMENTS] \nThese documents are about the following topic: '"
representation_model = OpenAI(client, prompt=prompt,model="gpt-4o")

In [ ]:
topics, probs = topic_model_migra.fit_transform(texts)
topic_model_migra.save('/content/drive/MyDrive/topic-specific-corpus-creation/models/model-minorities-sept.m')

2025-09-18 16:51:54,832 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/2494 [00:00<?, ?it/s]

2025-09-18 16:53:17,491 - BERTopic - Embedding - Completed ✓
2025-09-18 16:53:17,494 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-09-18 16:55:56,359 - BERTopic - Dimensionality - Completed ✓
2025-09-18 16:55:56,362 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-09-18 16:56:10,059 - BERTopic - Cluster - Completed ✓
2025-09-18 16:56:10,083 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-09-18 16:56:12,729 - BERTopic - Representation - Completed ✓
2025-09-18 16:56:15,281 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [ ]:
# Regenerate the BERTopic model
topics, probs = topic_model_migra.fit_transform(texts)
topic_model_migra.save('/content/drive/MyDrive/topic-specific-corpus-creation/models/model-minorities.m')

In [ ]:
topic_info = topic_model_migra.get_topic_info()

In [ ]:
display_dataframe_with_scroll(topic_info)

In [ ]:
topic_info.to_csv('/content/drive/MyDrive/topic-specific-corpus-creation/csv_files/topic_info_minorities_sept.csv', encoding='utf-8')

In [ ]:

topic_model_migra.save("/content/drive/MyDrive/topic-specific-corpus-creation/models/digitarium-25-safgetensors.m", serialization="safetensors", save_ctfidf=True, save_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

topic_model_migra.save("/content/drive/MyDrive/topic-specific-corpus-creation/models/digitarium-25-pytorch.m", serialization="pytorch", save_ctfidf=True, save_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# Method 3 - pickle
topic_model_migra.save("/content/drive/MyDrive/topic-specific-corpus-creation/models/digitarium-25.pk", serialization="pickle")

2025-09-18 17:11:53,351 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [ ]:
document_info = topic_model_migra.get_document_info(texts)

In [ ]:
document_info.to_csv('/content/drive/MyDrive/topic-specific-corpus-creation/csv_files/document_info_minorities_sept.csv', encoding='utf-8')

In [ ]:
topic_info['Name'].unique()

array(['-1_hungarn_deutschen_ungarn_böhmen',
       '0_hungarn_armee_feind_böhmen', '1_durchl_fürstl_ebendas_kais',
       '2_schiffe_flotte_schiffen_kriegs',
       '3_kirche_kirchen_cardinal_bischof',
       '4_silber_kästen_sessel_verschiedene',
       '5_königl_majestäten_majestät_könig',
       '6_türken_russischen_russische_russisch',
       '7_königl_kömgl_thom_elis', '8_zimmern_zimmer_kuchel_keller',
       '9_pferde_pferd_pferden_zigeuner',
       '10_ungarn_wasser_regen_schaden',
       '11_krankheit_er_griechen_seuche',
       '12_deutschen_deutsche_buchhandlung_büchern',
       '13_schneid_schmid_müller_schlossergs',
       '14_hungarn_titl_fürstl_grundbuch',
       '15_franzosen_frankreich_französischen_französische',
       '16_gott_du_heil_euch',
       '17_genugsam_anforderungen_widrigen_verlassenschaft',
       '18_feuer_feuers_brunst_häuser',
       '19_schweden_schwedische_stockholm_dänische',
       '20_durchl_wilh_guardarobba_didak',
       '21_haus_haushälfte_haunoldisches_frassisches', '22_majest_ma__',
       '23_anno_1730_wienn_biss', '24_ac_cum_ad_ex',
       '25_schätzung_dritten_zweyten_termin',
       '26_ungarn_stiftung_gebürtigen_präsentation',
       '27_persönlich_convoc_entweder_verlassenschaft',
       '28_gläubiger_denckscher_csamesiascher_kontischer',
       '29_anna_maria_seel_theresia', '30_wochen_binnen_jahr_obligation',
       '31_1000_5000_präm_10000',
       '32_effekten_schiegls_zinnerische_effecten',
       '33_alt_anna_mariah_dienstm',
       '34_schuldigen_feilbietung_anlangen_geschätzten',
       '35_mittags_mittag_abends_böhmen',
       '36_blumen_tulpen_bäumen_weingärten', '37_graf_lamberg_carl_baron',
       '38_churfürstl_chur_jhro_fürstl', '39_jhro_königl_nigl_jhrer',
       '40_frantzosen_frantzösische_frantzösischen_frantzösis',
       '41_magistrate_haupt_residenzstadt_bekannt',
       '42_hungarn_könig_boten_könige', '43_summa_darunter_kind_personen',
       '44_londen_britannien_brittannien_gross',
       '45_papier_gedruckt_schreib_ordinari',
       '46_foderung_verschuldeten_klage_forderung',
       '47_montag_sonntag_montags_dienstag',
       '48_wein_weine_weinm_weinmostes',
       '49_kauflustige_licit_deutsche_früh',
       '50_lotterie_losse_classe_looss',
       '51_septemb_september_vornehmung_septembr',
       '52_violon_pour_clavecin_violoncelle',
       '53_burgerl_burgersp_mayrberger_gewest',
       '54_römischen_rom_dalmatien_hungarn',
       '55_königl_möstl_kopp_kugler',
       '56_königl_xxxandem_kolonins_gxxxllxxx',
       '57_gebeth_carolivi_päpstl_pragæpragae',
       '58_rathstag_behandlung_sässen_abzuwarten',
       '59_französ_französischen_französis_französische',
       '60_wenn_masse_verschuldeten_gut', '61_amburgo_msi_7ne_140',
       '62_kayserl_zigeuner_ungarn_heute',
       '63_trompeten_paucken_trompeter_schall',
       '64_kupf_kupfer_kupfern_theile',
       '65_türken_kroatien_osmanen_bosnien',
       '66_griechen_1756_actum_1764', '67_1796_amort_may_wien',
       '68_novemb_november_monats_künftigen',
       '69_gräfl_reis_gräst_verwalteramte', '70_alt_79_versorgh_80',
       '71_25_joseph_johann_böhmen', '72_kais_serl_kai_regierende',
       '73_rathen_darum_sie_an', '74_ungarn_juden_hungarn_erben',
       '75_july_augusti_maynstrom_august',
       '76_pulver_storax_schierling_rosen',
       '77_dito_dienstag_kaiserl_mittag',
       '78_pyramide_marmor_mitte_wappen',
       '79_kunst_künstler_gallerie_natur',
       '80_freyhrn_freyherrl_frey_freyhr',
       '81_kaiserl_niemalen_cioccolata_angerühret',
       '82_amalia_kaiserin_erz_eleonora',
       '83_stadt_städten_residentz_kaiserstadt',
       '84_nuntius_nuntii_monsig_hungarn',
       '85_czech_konkurses_gerichte_gesammte',
       '86_sonn_evangelien_heiligen_gebettern',
       '87_oktob_october_oktober_wochenmärkte',
       '88_commissarien_commission_kommission_kommissare',
       '89_landesfürstl_magistrat_magistrate_oest',
       '90_deutschen_deutsche_michaeler_zeitungs',
       '91_blessirt_unwissende_capitapapaverisalbi_mohn', '92_ehew_ah__',
       '93_excell_excel_excellenz_euer',
       '94_kaiserl_regierende_beede_jhrer', '95_unzen_thle_dritter_vier',
       '96_liquers_blut_trocken_messer', '97_gräfl_von_sephst_lilien',
       '98_landrecht_landrechte_jeden_marschallischen',
       '99_licit_amort_essenzen_pöllin',
       '100_hochfürstl_hochw_jhro_jhrer',
       '101_holland_amsterdam_haag_7ne', '102_juden_stadt_alt_vor',
       '103_cont_conc_carnot_tököly',
       '104_letztemal_verhindernissen_rathstag_hören',
       '105_adjutant_general_secondleutenant_leutenant',
       '106_england_ungarn_frankreich_friedens',
       '107_cathol_javanisch_cattunen_garn', '108_1753_1751_1752_1750',
       '109_gilgenberg_miaskowski_zimmermann_oest',
       '110_paris_pariss_frankreich_französischen',
       '111_abends_mittags_königl_nachmittags',
       '112_verkaufen_täglich_haus_juden',
       '113_freyherrl_herrs_gerarde_heiligk',
       '114_febr_februarii_februar_expeditovero',
       '115_sterling_pfund_millionen_sterl', '116_jn_stadt_der_fruh',
       '117_april_samstag_montag_genua', '118_dito_den_freytag_und',
       '119_ro_ausmass_2788_2997', '120_eimer_fässer_gebirgweine_gewächs',
       '121_anemoni_turband_färbige_allerhand',
       '122_josepha_böhmen_josephst_peter',
       '123_ehedessen_auszufeilen_burgermeister_verwilliget',
       '124_allg_alt_barmh_cath', '125_leipz_ungeb_neapel_oenip',
       '126_alt_elisab_hülf_anna', '127_böhmen_prag_prager_corrti',
       '128_sachwalter_namhaft_beyzumessen_diensam',
       '129_eltern_nachkömmlingen_kinder_erblassers',
       '130_franz_alt_weissmann_weiss',
       '131_prinzessin_prinzessinnen_charlotte_prinzessinn',
       '132_kaiserl_kaiserspit_kaisersthée_69',
       '133_deto_stüferner_weissenkirchner_mugler',
       '134_hohh_hofer_bürgerl_päbstl', '135_math_alt_430_423',
       '136_tagl_tagw_brandstätter_kammerl',
       '137_sardinien_hungarn_parma_nacher',
       '138_1773_1772_steyr_laufende',
       '139_burgermeister_rath_geben_vernehmen',
       '140_böhmen_kaiserl_bernstein_alphabet',
       '141_pferde_faust_verkaufen_hengsten',
       '142_spanien_madrid_lateinischen_lateinisch',
       '143_realitäten_wambachersche_hauckische_weissische',
       '144_hans_franz_gottfried_juden',
       '145_behörig_gewalttrager_versehenen_falle',
       '146_krankenh_goekingk_pappenh_ubert',
       '147_cors_theile_hautb_thle', '148_december_decemb_rorate_vom',
       '149_octob_extrablat_octobris_eclio',
       '150_decemb_dedöcker_kreisamt_neuburg',
       '151_excell_nürnberg_cont_31', '152_gold_mach_wirt_beym',
       '153_ungarn_vieh_kühe_prag',
       '154_sicher_vorgehen_erbrecht_anzuhören',
       '155_glückwünsche_hungarn_abzustatten_complimenten',
       '156_rechtssache_angebrachte_gerichtsordnung_erblanden',
       '157_lesern_leser_briefe_herausgeber',
       '158_venedig_auss_decemb_juny',
       '159_regierung_abwesenden_gegenwärtig_daran',
       '160_hauptm_hausfr_hauskn_haushofmeist',
       '161_löbl_des_zarus_frepherrl', '162_deutschen_deutsche_il_30',
       '163_ungarn_böhmen_ungarischen_hungaris',
       '164_lisabon_portugal_portugall_lissabon',
       '165_wagen_lakirt_tafeln_tuch',
       '166_hungarn_diarii_wienerischen_verleger',
       '167_verordnung_löbl_hochlöbl_eines', '168_alt_wieden_68_rossau',
       '169_fortfah_ssigiährige_belehren_rthl',
       '170_oranien_arunculen_prinz_arnunculen',
       '171_früh_obbestimmten_licit_erscheinen', '172_cath_stief_eva_',
       '173_fest_heil_sonntags_festtag',
       '174_deutsche_baron_ungarn_obriste',
       '175_ferdinand_böhmen_braunschweig_ferdinands',
       '176_elis_elion_harder_jacobi',
       '177_hausmeister_wohnung_einzuholen_verlassen',
       '178_böhmen_kutsch_gebs_krankend',
       '179_frauenzimmer_stutzer_schönen_weiblichen',
       '180_superintendenten_burgerspitals_spitalmeister_spital',
       '181_kleebinder_spiegelritter_kohlischer_krayslisches',
       '182_feuerwerk_deutsche_deutschen_feuer',
       '183_dero_majestät_jhro_kaiserlich',
       '184_rheinstrom_nieder_vom_rheinstrohm',
       '185_schweitz_auss_december_scheyb',
       '186_kinskischen_anger_matzen_kleinmayerschen',
       '187_titl_ungarn_graf_maister',
       '188_verstoss_satzbrief_ausfertigung_gerathen',
       '189_frankfurt_deutschen_hamburg_augsburg',
       '190_catharina_cath_catholis_cathar',
       '191_reitter_juden_reitterin_erben',
       '192_1780_1782_presssburg_eisenärzt',
       '193_gräfin_adeliche_selig_stern',
       '194_ertz_hertzogin_böhmen_hertzo',
       '195_1789_convoc_juli_karansebes',
       '196_königl_königi_thrones_seine',
       '197_wornach_schaden_hütten_hüten',
       '198_jhro_kaiserin_königin_majestät',
       '199_unbekannt_noch_weiss_nicht', '200_juden_vlies_rabbiner_platz',
       '201_löbl_lobl_ludw_resolution', '202_fruh_uhr_kettel_woran',
       '203_kind_darunter_mutter_brachm',
       '204_christ_jesu_kinde_christian',
       '205_barb_barbarey_einederin_dietzin',
       '206_pension_summe_gulden_millionen',
       '207_leipzig_8vo_berlin_1764', '208_alt_militärsp_czech_deutsche',
       '209_perückenmachergewerb_jahnisches_pulvermacherin_altebollone',
       '210_deutsche_wien_vienne_beygesetzten',
       '211_augsb_augsp_augsbug_conv', '212_20000_2000_40000_200000',
       '213_bless_dechiliau_josephcuriel_leutenant',
       '214_deutschen_griechen_sprache_deutsch',
       '215_patent_böhmen_patents_kracksenträger',
       '216_strodl_stoll_schodterer_geschänk',
       '217_1798_böhmen_september_wien',
       '218_böhmen_ungarn_jnfanterieregiments_regiments',
       '219_1785_1784_1786_ok', '220_bill_bills_verlesen_commission',
       '221_polen_warschau_juny_aus',
       '222_meteorologische_sternwarte_beobachtungen_barometer',
       '223_frankf_frank_sebastian_gehollten',
       '224_kaiserl_jhro_jhre_altere',
       '225_leopoldst_leopold_leopoldi_alt',
       '226_frauenstift_frauenstifts_frauenzimmer_frauen',
       '227_allg_alt_38_26', '228_fürstl_entschlieffe_cell_sanft',
       '229_begnehmigung_versteigerung_waarenlager_käufer',
       '230_weiterem_burgischen_verzug_ausgefolget',
       '231_juni_bewilligung_juli_löbl',
       '232_kaiserl_sechszehen_unterzeichtet_tripolis',
       '233_1783_faustin_ordinariaten_citat',
       '234_1796_convoc_sogewiss_abgehandelt', '235_1785_juden_1786_wien',
       '236_königl_beygewognet_brieffenmaninalldortigemreichsehrnachderzuruckkunfftdes_ine',
       '237_sterl_viii__', '238_livorno_auss_december_july',
       '239_ǀǀ_millepedes_asseln_salpetermagnesie',
       '240_schuh_zoll_breit_juden', '241_burgl_mathiassche_berl_horn',
       '242_päpstl_priesters_priester_priest',
       '243_doct_dokt_chirurgus_arzt',
       '244_hochfürstl_general_feld_lieutenants',
       '245_jhre_königl_kasp_komp', '246_verordnung_juni_mixt_august',
       '247_1798_krems_1799_1810',
       '248_anzuhören_möchten_sicher_vorgehen',
       '249_mart_märz_sontag_monats',
       '250_retzer_reconvent_retractus_reverendiss',
       '251_parlaments_senat_parlements_versammlung',
       '252_kaufen_gedenken_früh_behausung',
       '253_juden_reichs_reichshofrathsagent_archivo',
       '254_frle_frider_fleischh_florini',
       '255_1762_künftigen_künfti_1762sten',
       '256_hungarn_böheim_körnerzehend_hoferischer',
       '257_jnländische_deutschen_1783_sonnabend',
       '258_verkauft_sold_seitel_gebrauchszetel',
       '259_jenner_ibid_mjttwoch_maesstrom',
       '260_stadtrichter_rath_bürgermeister_landesfürstl',
       '261_gefängnisse_trettungsfälle_vermöchte_geldstrafe',
       '262_deutsche_deutschen_diarium_jemand', '263_oeuv_blas__',
       '264_viol_vitriol_vitriolumdecypro_blauer',
       '265_nachtrag_diarium_wienerischen_1771',
       '266_zimmergs_zoll_zoraide_zählungen',
       '267_alt_19_lerchenf_laimgr',
       '268_parlament_parlaments_parlements_berufen',
       '269_wirthshaus_bestand_wisbauer_anerinneren',
       '270_verkaufen_haus_anzufragen_belieben',
       '271_erz_maria_anna_kron',
       '272_rossau_castoreum_bibergeil_rossbacher',
       '273_majestäten_jhro_krönungsceremonie_sultaninnen',
       '274_kais_nied_gräflich_von',
       '275_jahrhunderts_geistergeschichte_geister_geschichte',
       '276_magdalena_hertzogin_ertz_maria',
       '277_hoheit_hornung_durchl_fausta',
       '278_fahrnisse_madruzzische_demelmayers_hruschkinsche',
       '279_diarium_wiener_wienerisches_zeitung',
       '280_adam_adamischer_stellter_bernhard', '281_weine_weyl_befehl_',
       '282_arnold_washington_klinton_andre', '283_1772_wien_may_aktum',
       '284_farben_gesprengte_gesprangte_arunculen',
       '285_durchl_jhro_joschay_sr',
       '286_thürisches_ortsgericht_grundgericht_justiziair',
       '287_nacht_geschlafen_erwachen_dauerte', '288_stadt_vor_thurm_der',
       '289_burg_schloss_schlosse_buden', '290_deutschen_1719_wien_1716',
       '291_1745_1748_1740_1743',
       '292_landesfürstl_landsfürstl_camm_grossfürstl',
       '293_gestorbenen_testaments_denzstadt_resi',
       '294_amtskanzley_freyherrl_schwadorf_amts',
       '295_stimmen_kongress_mehrheit_kongresse',
       '296_uber_urthl_zang_glüender', '297_monsig_mons_trouvent_chez',
       '298_fürstl_grast_des_von', '299_1796_ungeb_change_florins',
       '300_winterm_wintermon_winter_eisfelders',
       '301_card_hungarn_kartenplänen_karten',
       '302_griechen_religion_religions_pasquillantisch',
       '303_caffeehaus_durchhaus_haarbeutelgewölbe_schmeckenden',
       '304_sultan_böhmen_sultans_gross',
       '305_wallis_prinzen_prinz_blattern',
       '306_convoc_widerspruch_welcher_', '307_1658_licit_1659_1640',
       '308_schneidermeist_schneiderm_schneiderns_schneider',
       '309_pol_ungarn_arcivescovo_eminenz',
       '310_holzinger_hofmann_schmied_georg',
       '311_lmprimatur_artikel_bedingung_erzogene',
       '312_auflage_verbesserte_editio_accurata',
       '313_1731_1746_wien_1730', '314_österr_öster_östl_nied',
       '315_pfänder_einkommenden_kundschaftsbogen_versetzt',
       '316_1777_1778_aussenbleibungsfalle_commende',
       '317_gen_anmerkun_genen_findliche',
       '318_gerichtsordnung_erblande_richteramtshand_redoute',
       '319_juny_maesstrom_freptag_18ten',
       '320_hungarn_haag_holland_niederlande',
       '321_stiftsgrundbuch_diesseitigen_gedenken_baarer',
       '322_audienz_publikum_zuschauer_publik',
       '323_frieden_amerika_friedens_nation',
       '324_licht_lampen_lampe_lichter',
       '325_1781_georgizeit_anfangend_künftige',
       '326_wasser_wixe_allerfeinsten_putzen',
       '327_steif_gebund_bogen_pfündige',
       '328_löbl_bourne_reitenauer_appel', '329_hefte_21ten_allg_26',
       '330_ceremonien_händen_kleidern_cronen',
       '331_bücher_bibliothekdien_lektüre_andertes',
       '332_pcto_überkommener_cent_garnitur',
       '333_1765_1767_1766_wichenen', '334_flandern_auss_jenner_gent',
       '335_erzbischöfl_marq_botschafter_',
       '336_censoren_censor_censur_censursbewilligung',
       '337_jenner_elbstrom_sambstag_auss', '338_1779_musgrave_iius_dec',
       '339_40_20_gebund_steif', '340_kauflustige_licit_einfinden_ort',
       '341_1764_1760_hässliche_weiber',
       '342_wien_sonntagspredigten_vergleichung_residentz',
       '343_kaiserl_uhlfeld_wienerisches_jhrer',
       '344_hungarn_türken_böhmen_gebürtig',
       '345_inpulvere_pulver_sandbeeren_blätter',
       '346_deutschen_hungarn_enthaltend_getaufften',
       '347_sangin_chur_jaguschinski_jwa',
       '348_pens_stift_heil_eipeldanerbriefe',
       '349_bedient_schlafrockschneiders_saniyni_leporin',
       '350_königl_der_dem_von',
       '351_hungarn_preussischen_preuss_preussische',
       '352_apost_nämlich_se_jhre', '353_pfründl_pfeffer_pflaster_stamp',
       '354_1771_terische_hofstadtbehausung_haftend',
       '355_reichsfreyherrl_reichsgräfl_amtskanzley_lordmaire',
       '356_jahrs_jahren_jahr_jah', '357_zug_häu_procession_anfang',
       '358_1795_citat_regierungsverordnung_leihen',
       '359_eichhörnen_spezies_gattung_rier',
       '360_kayserl_jhro_kays_pomposester',
       '361_dank_abzustatten_verbindet_besuche',
       '362_magd_fehringerin_wit_alt',
       '363_fortsetzung_folgt_continuation_künftig',
       '364_termino_2do_1mo_fallenden',
       '365_landesregierung_oberamtsregierung_oberamts_bestättiget',
       '366_zusammen_pavia_dunant_giacomoni',
       '367_thol_preuss_preussis_thlr',
       '368_paris_märz_exemplaire_groskanzler',
       '369_invigiliren_wornach_richten_recht',
       '370_reitknechte_gesetz_belegt_strafung',
       '371_deleg_clavier_detto_abschrift',
       '372_paul_kraus_krauss_comödienhaus',
       '373_buchdruckern_hof_holzversilb_holzapfel',
       '374_feilbietung_gegentheiligen_geschätzten_schuldigen',
       '375_hungarn_spanien_spanischen_portugesischen',
       '376_venus_jupiter_stralen_comet',
       '377_richten_wornach_wissen_jeder',
       '378_hisp_mann_angewachsen_getröste',
       '379_1759_1758_exelus_anticipationen',
       '380_nied_henn_nistrationsregistrat_admi',
       '381_kirche_beschädiget_gebäude_kloster',
       '382_ihrs_dziali_merida_maiest',
       '383_fortepiano_grosses_verkaufen_gutes',
       '384_fischen_fisch_fischkäuflerin_fische',
       '385_nigl_kö_nigricant_wje',
       '386_juden_böhmen_zugelassen_judenschaft',
       '387_gedruckt_kaiserl_ankünankündigung_geschmackte',
       '388_1761_anhang_samstags_mittwochs',
       '389_böhmen_deutschen_kupfertafeln_baukunst',
       '390_böhmen_8vo_dresden_königsberg',
       '391_appell_appel_belteb_ametist', '392_brosch_48_45_24',
       '393_todt_mayt__', '394_27_28_11_11½',
       '395_1775_1773_kolsburg_wien',
       '396_haag_friedens_holland_britannische',
       '397_musik_oper_parodie_music', '398_3000_30000_gulden_300000',
       '399_amtsverwaltung_gräfl_speigen_unmittelbarkeit',
       '400_kais_kumin_ludov_serl',
       '401_hyacinten_gefüllte_hyacinthen_weisse',
       '402_satzbrief_satzbriefe_briefe_ruhmtüchtig',
       '403_1756_1755_17775_stuttgard', '404_math_calculat_kind_alt',
       '405_kayserin_hungarn_kayserl_verwittibte',
       '406_richter_rath_landesfürstl_rathgeb',
       '407_eimer_pillichstorf_joch_guts',
       '408_heinr_heil_heiderisches_hebelaker',
       '409_würdigen_schotten_lieben_stifts',
       '410_verordnung_nachmittagsstunden_hochlöbl_dies',
       '411_obligation_obligationen_schedlische_obligatio',
       '412_brücke_böhmen_brücken_geschlagen',
       '413_1791_convoc_juni_1789', '414_joch_64_dienstbar_herrschaft',
       '415_terni_jenem_terno_sub',
       '416_hochlöbl_bewilligung_genehmhal_beförderet',
       '417_band_bände_erschienenen_pränumerirt',
       '418_kuefstein_kerschner_kirchberg_32tes',
       '419_mayerische_mayer_gläubiger_mayerey',
       '420_wissenschaft_jedermanns_landesregierung_chemie',
       '421_1772_1771273_177273_40451',
       '422_1749_rousset_leiptig_vermehret',
       '423_phil_philos_doct_kengires', '424_haus___',
       '425_leop_morbis_leonh_valentin',
       '426_alters_gestorben_alter_jahr',
       '427_edict_offene_wollen_erinneren',
       '428_1771_jänner_osterzell_märz',
       '429_wagner_wagneris_wagners_2ter',
       '430_mjttwoch_december_augusti_herschaften',
       '431_fox_bill_commissaire_stimmen',
       '432_warnenden_belehrenden_spiele_oh',
       '433_1776_november_wien_august',
       '434_deutschen_verkaufen_wallach_reitpferde',
       '435_burgl_färbermeisters_jetzin_hubmer',
       '436_majest_jhro_jhre_jh', '437_kaiserin_beutel_jhre_majestät',
       '438_50_50000_bankozettel_lohren', '439_schw___',
       '440_hungarn_taxberg_saxe_landbothe',
       '441_jnsiegel_jsabella_getheilet_folio',
       '442_thuen_landgerichts_offenen_landrichter',
       '443_brittannien_gross_high_lord',
       '444_leopoldstadt_süssenbrunn_leopoldau_leopold',
       '445_revisionsamte_drucke_zulassung_originals',

In [ ]:
pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.3 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.6 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 25.8 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 29.9 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 11.2 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [8]:
loaded_model = BERTopic.load("/content/drive/MyDrive/topic-specific-corpus-creation/models/digitarium-25-safgetensors.m")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
import gensim
import nltk
from nltk.corpus import stopwords
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora import Dictionary

In [ ]:
from collections import defaultdict

In [ ]:
# Ensure you have stopwords downloaded
nltk.download('stopwords')
stop_words = stopwords.words('german')  # Or 'english', 'french', etc.

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
def preprocess(text):
    result = []
    for token in gensim.utils.simple_preprocess(text):
        if token not in german_stopwords:
            result.append(token)
    return result

In [ ]:
german_stopwords = stopwords.words('german')

In [ ]:
processed_docs = [preprocess(text) for text in texts]

In [ ]:
dictionary = Dictionary(processed_docs)
corpus = [dictionary.doc2bow(doc) for doc in processed_docs]

In [ ]:
topic_words = loaded_model.get_topics()
topics_list = [[word for word, _ in topic_words[topic]] for topic in topic_words if topic != -1]

In [ ]:
coherence_model_bert = CoherenceModel(topics=topics_list, texts=processed_docs, dictionary=dictionary, coherence='c_v')
coherence_bert = coherence_model_bert.get_coherence()
print(f'BERTopic Coherence Score: {coherence_bert}')

BERTopic Coherence Score: 0.4210212134963046

In [9]:
topic_info = loaded_model.get_topic_info()

In [ ]:
topic_info.head(20)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,40184,-1_hungarn_deutschen_ungarn_böhmen,"[hungarn, deutschen, ungarn, böhmen, deutsche,...",NaN
1,0,2963,0_hungarn_armee_feind_böhmen,"[hungarn, armee, feind, böhmen, general, regim...",NaN
2,1,1555,1_durchl_fürstl_ebendas_kais,"[durchl, fürstl, ebendas, kais, statt, gebund,...",NaN
3,2,1345,2_schiffe_flotte_schiffen_kriegs,"[schiffe, flotte, schiffen, kriegs, admiral, s...",NaN
4,3,872,3_kirche_kirchen_cardinal_bischof,"[kirche, kirchen, cardinal, bischof, heiligkei...",NaN
5,4,843,4_silber_kästen_sessel_verschiedene,"[silber, kästen, sessel, verschiedene, licitan...",NaN
6,5,667,5_königl_majestäten_majestät_könig,"[königl, majestäten, majestät, könig, hungarn,...",NaN
7,6,528,6_türken_russischen_russische_russisch,"[türken, russischen, russische, russisch, russ...",NaN
8,7,511,7_königl_kömgl_thom_elis,"[königl, kömgl, thom, elis, , , , , , ]",NaN
9,8,385,8_zimmern_zimmer_kuchel_keller,"[zimmern, zimmer, kuchel, keller, stock, stall...",NaN
10,9,382,9_pferde_pferd_pferden_zigeuner,"[pferde, pferd, pferden, zigeuner, roma, wägen...",NaN
11,10,378,10_ungarn_wasser_regen_schaden,"[ungarn, wasser, regen, schaden, kälte, wetter...",NaN
12,11,345,11_krankheit_er_griechen_seuche,"[krankheit, er, griechen, seuche, ihn, ihm, to...",NaN
13,12,343,12_deutschen_deutsche_buchhandlung_büchern,"[deutschen, deutsche, buchhandlung, büchern, b...",NaN
14,13,337,13_schneid_schmid_müller_schlossergs,"[schneid, schmid, müller, schlossergs, schuhma...",NaN
15,14,300,14_hungarn_titl_fürstl_grundbuch,"[hungarn, titl, fürstl, grundbuch, adeliche, s...",NaN
16,15,294,15_franzosen_frankreich_französischen_französi...,"[franzosen, frankreich, französischen, französ...",NaN
17,16,289,16_gott_du_heil_euch,"[gott, du, heil, euch, pol, deinen, hungarn, e...",NaN
18,17,288,17_genugsam_anforderungen_widrigen_verlassensc...,"[genugsam, anforderungen, widrigen, verlassens...",NaN
19,18,275,18_feuer_feuers_brunst_häuser,"[feuer, feuers, brunst, häuser, brand, flammen...",NaN

In [21]:
document_info = loaded_model.get_document_info(texts)

# **Dynamic Topic Modelling**



*   training the DTM model from the global topic representation (texts and timestamps are previously created lists
*   number of bins = 60, as there is over 100 timestamps, they need to be put into bins to ensure quality of model

In [ ]:

topics_over_time = loaded_model.topics_over_time(texts, timestamps,
                                                global_tuning=True, evolution_tuning=True, nr_bins=60)

54it [01:43,  1.92s/it]

In [ ]:
# Convert to dataframe
dtm_df = pd.DataFrame(topics_over_time)

# Save to CSV
dtm_df.to_csv(
    "/content/drive/MyDrive/topic-specific-corpus-creation/csv_files/topics_over_time-digi-sept.csv",
    index=False
)

In [ ]:
topic_words = loaded_model.get_topics()
topics_list = [[word for word, _ in topic_words[topic]] for topic in topic_words if topic != -1]

In [ ]:
for i, topic in enumerate(topics_list[:5]):
    print(f"Topic {i}: {topic}")

Topic 0: ['hungarn', 'armee', 'feind', 'böhmen', 'general', 'regiment', 'ungarn', 'lager', 'türken', 'truppen']
Topic 1: ['durchl', 'fürstl', 'ebendas', 'kais', 'statt', 'gebund', 'leopst', 'seel', 'löbl', 'hoheit']
Topic 2: ['schiffe', 'flotte', 'schiffen', 'kriegs', 'admiral', 'schiff', 'hafen', 'see', 'schif', 'meer']
Topic 3: ['kirche', 'kirchen', 'cardinal', 'bischof', 'heiligkeit', 'päpstl', 'ertz', 'türken', 'bischöfl', 'cardinälen']
Topic 4: ['silber', 'kästen', 'sessel', 'verschiedene', 'licitando', 'tische', 'zinn', 'gold', 'verkauft', 'spiegel']

In [ ]:
import pandas as pd
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora import Dictionary

# --- Reuse your variables ---
# texts            -> list[str]
# timestamps       -> list[datetime-like or str]
# processed_docs   -> list[list[str]] from your preprocess()
# loaded_model     -> your BERTopic model

# 1) (Re)build a clean topics_list (strings only, no empty topics)
topic_words = loaded_model.get_topics()
topics_list = []
for tid, word_scores in topic_words.items():
    if tid == -1:
        continue
    words = [w for (w, _) in word_scores if isinstance(w, str) and len(w)]
    if words:
        topics_list.append(words)

# 2) Build a frame to group documents into the same monthly bins as your DTM labels (e.g., 'YYYY-MM')
df_coh = pd.DataFrame({
    "processed": processed_docs,
    "timestamp": pd.to_datetime(timestamps, errors="coerce")
})
df_coh = df_coh.dropna(subset=["timestamp"])
df_coh["bin"] = df_coh["timestamp"].dt.to_period("M").astype(str)

# 3) Compute c_v coherence per bin (filter topics to the bin’s vocabulary to avoid the Gensim error)
results = []
for bin_label, group in df_coh.groupby("bin", sort=True):
    bin_docs = group["processed"].tolist()

    # skip tiny bins
    if len(bin_docs) < 5:
        continue

    bin_dict = Dictionary(bin_docs)
    vocab = set(bin_dict.token2id.keys())

    # filter topic words to those present in this bin’s vocab; drop empty topics
    filtered_topics = [[w for w in t if w in vocab] for t in topics_list]
    filtered_topics = [t for t in filtered_topics if len(t) >= 2]

    # if no overlap, skip (prevents "unable to interpret topic..." error)
    if len(filtered_topics) < 2:
        continue

    cm = CoherenceModel(
        topics=filtered_topics,
        texts=bin_docs,
        dictionary=bin_dict,
        coherence="c_v"
    )
    score = cm.get_coherence()
    results.append({
        "time_bin": bin_label,
        "coherence_c_v": score,
        "n_docs": len(bin_docs),
        "vocab_size": len(vocab),
        "n_topics_used": len(filtered_topics)
    })

KeyboardInterrupt:

In [ ]:
# 4) Save results
coh_df = pd.DataFrame(results).sort_values("time_bin")
coh_df.to_csv("/content/drive/MyDrive/topic-specific-corpus-creation/csv_files/dtm_coherence.csv", index=False)
print(coh_df)

   time_bin  coherence_c_v  n_docs  vocab_size  n_topics_used
0   1703-08       0.302857     289        2195            173
1   1703-11       0.334788     104        1180            145
2   1705-01       0.283236     234        1919            164
3   1705-05       0.311982     116        1139            104
4   1705-09       0.360046     425        2441            201
5   1706-01       0.346394      86        1132            118
6   1706-02       0.332406     125        1609            144
7   1706-05       0.344176      94        1386            136
8   1706-12       0.338685     188        1665            167
9   1707-01       0.317293     210        1976            194
10  1707-04       0.321115     161        1412            151
11  1707-11       0.323592     101         957            114
12  1708-08       0.348386     120        1032            130
13  1708-10       0.316994     246        1902            173
14  1709-06       0.332535     100        1006            119
15  1709-10       0.326436     129        1184            120
16  1709-11       0.358499     108        1105            104
17  1709-12       0.320557     198        2190            196
18  1710-01       0.336568     171        1745            149
19  1710-09       0.322129     284        1915            159
20  1711-02       0.376309      79         826             92
21  1711-04       0.359783     129         894            124
22  1711-07       0.349060     127        1478            162
23  1711-12       0.293347     538        3845            257
24  1712-05       0.328133     296        1808            165
25  1712-11       0.369870     260        1618            174
26  1714-01       0.317548     139        1520            161
27  1714-02       0.313612      75        1147            138
28  1714-07       0.356691      81         951            119
29  1715-06       0.353032     161        1450            157
30  1715-07       0.309188     237        2759            217
31  1716-08       0.325750     515        3910            264
32  1719-01       0.318605      58        1061            126
33  1719-07       0.325443     126        1969            178
34  1719-11       0.333461     139        1840            182
35  1720-01       0.381450      53        1006             99
36  1721-04       0.335226     190        2710            219
37  1721-05       0.362376     124        2138            187
38  1722-01       0.322882      86        1139            112
39  1722-10       0.319670     443        3681            265
40  1722-11       0.332797     320        3020            242
41  1725-02       0.272667     168        1530            188
42  1725-05       0.331123     661        5297            324
43  1726-09       0.311001     944        6470            369
44  1727-02       0.315384     127        1814            171
45  1727-11       0.310116     763        5456            332
46  1728-07       0.292888     524        4080            290
47  1728-08       0.325875     287        1850            185
48  1728-11       0.324166     159        1652            169
49  1729-04       0.310741     750        5779            341
50  1730-03       0.299819     482        4048            269
51  1730-04       0.328820     483        4137            316
52  1731-04       0.333365     202        2025            208
53  1731-05       0.337571     309        3369            260
54  1731-06       0.318685     156        1718            175
55  1731-12       0.295503     187        2076            212
56  1732-02       0.301711     136        1741            209
57  1732-05       0.331658     247        2908            255
58  1732-06       0.345306     232        1752            195
59  1732-07       0.291204     143        1547            177

In [ ]:
average_coherence = coh_df["coherence_c_v"].mean()
print(f"\n📊 Average coherence over all bins: {average_coherence:.4f}")

📊 Average coherence over all bins: 0.3273

In [ ]:
def calculate_topic_diversity(model, top_k=10):
    # Get topic words, skip topic -1 (outliers)
    topics = model.get_topics()

    topic_word_sets = [
        [word for word, _ in words[:top_k]]
        for topic_id, words in topics.items()
        if topic_id != -1 and words
    ]

    # Flatten the list of topic words
    all_words = [word for topic in topic_word_sets for word in topic]
    unique_words = set(all_words)

    # Compute diversity
    total_words = len(all_words)
    diversity = len(unique_words) / total_words if total_words > 0 else 0

    return diversity

In [ ]:
diversity_score = calculate_topic_diversity(loaded_model, top_k=10)
print(f"📚 Topic Diversity (top 10 words): {diversity_score:.4f}")

📚 Topic Diversity (top 10 words): 0.7397

- 0_hungary_army_enemy_bohemia


- 6_turks_russian_russian_russian
- 9_horses_horse_horses_gypsies

- 10_hungary_water_rain_damage
- 65_türken_kroatien_osmanen_bosnien
- 74_hungary_jews_hungary_heirs
- 112_sell_house_daily_jews
- 200_jews_fleece_rabbi_square
- 191_reitter_juden_reitterin_erben
- 218_Bohemia_Hungary_Jnfanterieregiments_regiments
- 386_jews_bohemia_admitted_jewishness
- 221_polen_warschau_juny_aus

In [18]:
relevant_topic_ids = [0, 6, 9, 10, 65, 74, 112, 200, 191, 218, 386, 221]

In [22]:
document_info

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document
0,Auss Wienn von biss Augusti 1703.,-1,-1_hungarn_deutschen_ungarn_böhmen,"[hungarn, deutschen, ungarn, böhmen, deutsche,...",NaN,hungarn - deutschen - ungarn - böhmen - deutsc...,False
1,DEn dito hat man dass die Land Militz welche ...,0,0_hungarn_armee_feind_böhmen,"[hungarn, armee, feind, böhmen, general, regim...",NaN,hungarn - armee - feind - böhmen - general - r...,False
2,Wie verlautet seynd Käyserl.,1,1_durchl_fürstl_ebendas_kais,"[durchl, fürstl, ebendas, kais, statt, gebund,...",NaN,durchl - fürstl - ebendas - kais - statt - geb...,False
3,in stehende Regimenter beordert ihren March ...,0,0_hungarn_armee_feind_böhmen,"[hungarn, armee, feind, böhmen, general, regim...",NaN,hungarn - armee - feind - böhmen - general - r...,False
4,Gestern ist ein Courier von der Armée auss Jta...,40,40_frantzosen_frantzösische_frantzösischen_fra...,"[frantzosen, frantzösische, frantzösischen, fr...",NaN,frantzosen - frantzösische - frantzösischen - ...,False
...,...,...,...,...,...,...,...
79777,"Praktische französische Grammatik, wodurch man...",-1,-1_hungarn_deutschen_ungarn_böhmen,"[hungarn, deutschen, ungarn, böhmen, deutsche,...",NaN,hungarn - deutschen - ungarn - böhmen - deutsc...,False
79778,"Von Johann Valentin Meidinger, Lehrer der fran...",-1,-1_hungarn_deutschen_ungarn_böhmen,"[hungarn, deutschen, ungarn, böhmen, deutsche,...",NaN,hungarn - deutschen - ungarn - böhmen - deutsc...,False
79779,Fünfzehnte durchaus verbesserte und nach Waill...,312,312_auflage_verbesserte_editio_accurata,"[auflage, verbesserte, editio, accurata, origi...",NaN,auflage - verbesserte - editio - accurata - or...,False
79780,Frankfurt und Leipzig 1799.,-1,-1_hungarn_deutschen_ungarn_böhmen,"[hungarn, deutschen, ungarn, böhmen, deutsche,...",NaN,hungarn - deutschen - ungarn - böhmen - deutsc...,False
79781,"38 Bogen stark, auf schönen weissen Druckpapie...",45,45_papier_gedruckt_schreib_ordinari,"[papier, gedruckt, schreib, ordinari, abwischp...",NaN,papier - gedruckt - schreib - ordinari - abwis...,False

In [ ]:
# Filter the document_info DataFrame
relevant_docs = document_info[document_info["Topic"].isin(relevant_topic_ids)]

# Save to CSV
relevant_docs.to_csv(
    "/content/drive/MyDrive/topic-specific-corpus-creation/csv_files/relevant_docs_digi_25.csv",
    index=False
)

In [ ]:
loaded_model.visualize_topics_over_time(topics_over_time, top_n_topics=10, topics=[0,6,65, 74, 191, 386, 221, 218 ] )

In [ ]:
loaded_model.visualize_topics_over_time(topics_over_time, topics=[0,1, 2, 3, 4, 5 ])

In [ ]:
loaded_model.visualize_barchart()

Evauating BERTopic model with coherence metric

1.   issues with evaluation of modular, transformer-based library with coherence -https://github.com/MaartenGr/BERTopic/issues/2009, https://github.com/MaartenGr/BERTopic/issues/437
2.   human evaluation seems to be necessary - in the future a gold standard would be needed

In [23]:
filtered_doc_info = document_info[document_info["Topic"].isin(relevant_topic_ids)].copy()

In [24]:
topic_meta = topic_info[["Topic", "Representation"]]
filtered_doc_info = filtered_doc_info.merge(topic_meta, on="Topic", suffixes=('', '_topic'))

In [25]:
filtered_doc_info = filtered_doc_info.merge(
    df_digi[["text", "date"]],
    left_on="Document",
    right_on="text",
    how="left"
)

In [26]:
df_digi_sorted = df_digi.sort_values(by=["date"]).reset_index(drop=True)
df_digi_sorted["position"] = df_digi_sorted.index
text_to_index = df_digi_sorted.set_index("text")["position"].to_dict()

In [27]:
def get_context(text, date):
    idx = text_to_index.get(text, None)
    if idx is None:
        return pd.Series([None, None])

    same_day_docs = df_digi_sorted[df_digi_sorted["date"] == date]
    same_day_texts = same_day_docs["text"].tolist()

    try:
        local_idx = same_day_texts.index(text)
    except ValueError:
        return pd.Series([None, None])

    # Get previous two and next two texts
    prev_docs = same_day_texts[max(0, local_idx - 2):local_idx]
    next_docs = same_day_texts[local_idx + 1:local_idx + 3]

    return pd.Series([
        " ".join(prev_docs),  # context_before
        " ".join(next_docs)   # context_after
    ])

# Step 6: Apply context function
filtered_doc_info[["context_before", "context_after"]] = filtered_doc_info.apply(
    lambda row: get_context(row["text"], row["date"]),
    axis=1
)

In [28]:
final_df = filtered_doc_info[["text", "date", "Topic", "Representation", "context_before", "context_after"]]

In [29]:
final_df.to_csv(
    "/content/drive/MyDrive/topic-specific-corpus-creation/csv_files/relevant_docs_digi_25_with_context.csv",
    index=False
)